development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: emabox_dev
  pool: 5
  username: usuarioEMA
  password: acdc619mljj

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: emabox_test
  pool: 5
  username: usuarioEMA
  password: acdc619mljj

production:
  adapter: postgresql
  reconnect: false
  host: ec2-54-243-150-10.compute-1.amazonaws.com
  database: d493n89l8v0512
  pool: 5
  username: dehsowzjyarlil
  password: 8b44ff44052166ed81545f93667171e21a946fe8128987ef7ac277f98a67e5c6
