development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: emabox_dev
  pool: 5
  username: usuarioEMA
  password: acdc619mljj

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: emabox_test
  pool: 5
  username: usuarioEMA
  password: acdc619mljj

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: emabox
  pool: 5
  username: usuarioEMA
  password: acdc619mljj
